-- =============================================================================
-- CONSUMPTION INSIGHT VIEWS - Project Helios (Trial: 200 credits/month)
-- =============================================================================
-- Role: ACCOUNTADMIN (required for ACCOUNT_USAGE access)
-- Warehouse: COMPUTE_WH (monitoring queries)
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

USE DATABASE HELIOS_ANALYTICS_DB;
USE SCHEMA PUBLIC;

-- =============================================================================
-- 1. V_DAILY_CREDIT_SUMMARY - Daily credit totals for trend spotting
-- =============================================================================
CREATE OR REPLACE VIEW HELIOS_ANALYTICS_DB.PUBLIC.V_DAILY_CREDIT_SUMMARY AS
SELECT 
    DATE_TRUNC('DAY', START_TIME)::DATE AS USAGE_DATE,
    ROUND(SUM(CREDITS_USED), 4) AS TOTAL_CREDITS,
    ROUND(SUM(CREDITS_USED_COMPUTE), 4) AS COMPUTE_CREDITS,
    ROUND(SUM(CREDITS_USED_CLOUD_SERVICES), 4) AS CLOUD_SERVICES_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_DATE())
GROUP BY DATE_TRUNC('DAY', START_TIME)::DATE
ORDER BY USAGE_DATE DESC;

-- =============================================================================
-- 2. V_WAREHOUSE_DAILY_USAGE - Per-warehouse daily breakdown
-- =============================================================================
CREATE OR REPLACE VIEW HELIOS_ANALYTICS_DB.PUBLIC.V_WAREHOUSE_DAILY_USAGE AS
SELECT 
    DATE_TRUNC('DAY', START_TIME)::DATE AS USAGE_DATE,
    WAREHOUSE_NAME,
    ROUND(SUM(CREDITS_USED), 4) AS TOTAL_CREDITS,
    ROUND(SUM(CREDITS_USED_COMPUTE), 4) AS COMPUTE_CREDITS,
    ROUND(SUM(CREDITS_USED_CLOUD_SERVICES), 4) AS CLOUD_SERVICES_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_DATE())
    AND WAREHOUSE_NAME IN ('INGEST_WH', 'TRANSFORM_WH', 'REPORTING_WH', 'CORTEX_WH', 'COMPUTE_WH')
GROUP BY DATE_TRUNC('DAY', START_TIME)::DATE, WAREHOUSE_NAME
ORDER BY USAGE_DATE DESC, TOTAL_CREDITS DESC;

-- =============================================================================
-- 3. V_WAREHOUSE_HOURLY_PATTERN - Identify peak usage hours
-- =============================================================================
CREATE OR REPLACE VIEW HELIOS_ANALYTICS_DB.PUBLIC.V_WAREHOUSE_HOURLY_PATTERN AS
SELECT 
    WAREHOUSE_NAME,
    HOUR(START_TIME) AS HOUR_OF_DAY,
    ROUND(AVG(CREDITS_USED), 6) AS AVG_CREDITS,
    ROUND(SUM(CREDITS_USED), 4) AS TOTAL_CREDITS,
    COUNT(*) AS SAMPLE_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(DAY, -14, CURRENT_DATE())
    AND WAREHOUSE_NAME IN ('INGEST_WH', 'TRANSFORM_WH', 'REPORTING_WH', 'CORTEX_WH', 'COMPUTE_WH')
GROUP BY WAREHOUSE_NAME, HOUR(START_TIME)
ORDER BY WAREHOUSE_NAME, HOUR_OF_DAY;

-- =============================================================================
-- 4. V_TOP_QUERIES_BY_COST - Most expensive queries (last 7 days)
-- =============================================================================
CREATE OR REPLACE VIEW HELIOS_ANALYTICS_DB.PUBLIC.V_TOP_QUERIES_BY_COST AS
SELECT 
    QUERY_ID,
    QUERY_PARAMETERIZED_HASH,
    USER_NAME,
    WAREHOUSE_NAME,
    ROUND(CREDITS_ATTRIBUTED_COMPUTE, 6) AS CREDITS_USED,
    START_TIME,
    DATEDIFF('SECOND', START_TIME, END_TIME) AS DURATION_SECONDS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY
WHERE START_TIME >= DATEADD(DAY, -7, CURRENT_DATE())
    AND CREDITS_ATTRIBUTED_COMPUTE > 0
ORDER BY CREDITS_ATTRIBUTED_COMPUTE DESC
LIMIT 100;

-- =============================================================================
-- 5. V_USER_CONSUMPTION - Credit usage by user
-- =============================================================================
CREATE OR REPLACE VIEW HELIOS_ANALYTICS_DB.PUBLIC.V_USER_CONSUMPTION AS
SELECT 
    USER_NAME,
    COUNT(*) AS QUERY_COUNT,
    ROUND(SUM(CREDITS_ATTRIBUTED_COMPUTE), 4) AS TOTAL_CREDITS,
    ROUND(AVG(CREDITS_ATTRIBUTED_COMPUTE), 6) AS AVG_CREDITS_PER_QUERY,
    ROUND(MAX(CREDITS_ATTRIBUTED_COMPUTE), 6) AS MAX_QUERY_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY
WHERE START_TIME >= DATEADD(DAY, -7, CURRENT_DATE())
    AND CREDITS_ATTRIBUTED_COMPUTE > 0
GROUP BY USER_NAME
ORDER BY TOTAL_CREDITS DESC
LIMIT 50;

-- =============================================================================
-- 6. V_DATABASE_STORAGE - Storage by Helios database
-- =============================================================================
CREATE OR REPLACE VIEW HELIOS_ANALYTICS_DB.PUBLIC.V_DATABASE_STORAGE AS
SELECT 
    DATABASE_NAME,
    USAGE_DATE,
    ROUND(AVERAGE_DATABASE_BYTES / POWER(1024, 3), 4) AS STORAGE_GB,
    ROUND(AVERAGE_DATABASE_BYTES / POWER(1024, 4), 6) AS STORAGE_TB,
    ROUND(AVERAGE_FAILSAFE_BYTES / POWER(1024, 3), 4) AS FAILSAFE_GB
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
WHERE DATABASE_NAME LIKE 'HELIOS%'
    AND USAGE_DATE >= DATEADD(DAY, -30, CURRENT_DATE())
ORDER BY USAGE_DATE DESC, STORAGE_GB DESC;

-- =============================================================================
-- 7. V_CORTEX_AI_USAGE - Cortex function costs (for AI layer)
-- =============================================================================
CREATE OR REPLACE VIEW HELIOS_ANALYTICS_DB.PUBLIC.V_CORTEX_AI_USAGE AS
SELECT 
    DATE_TRUNC('DAY', START_TIME)::DATE AS USAGE_DATE,
    FUNCTION_NAME,
    MODEL_NAME,
    ROUND(SUM(TOKEN_CREDITS), 6) AS TOTAL_CREDITS,
    SUM(TOKENS) AS TOTAL_TOKENS,
    COUNT(*) AS CALL_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_FUNCTIONS_USAGE_HISTORY
WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_DATE())
GROUP BY DATE_TRUNC('DAY', START_TIME)::DATE, FUNCTION_NAME, MODEL_NAME
ORDER BY USAGE_DATE DESC, TOTAL_CREDITS DESC;

-- =============================================================================
-- 8. V_RESOURCE_MONITOR_STATUS - Current monitor quotas vs usage
-- =============================================================================
CREATE OR REPLACE VIEW HELIOS_ANALYTICS_DB.PUBLIC.V_RESOURCE_MONITOR_STATUS AS
SELECT 
    NAME AS MONITOR_NAME,
    CREDIT_QUOTA,
    USED_CREDITS,
    ROUND(REMAINING_CREDITS, 4) AS REMAINING_CREDITS,
    ROUND((USED_CREDITS::FLOAT / NULLIF(CREDIT_QUOTA::FLOAT, 0)) * 100, 2) AS PCT_CONSUMED,
    NOTIFY AS NOTIFY_THRESHOLD,
    SUSPEND AS SUSPEND_THRESHOLD,
    SUSPEND_IMMEDIATE AS SUSPEND_IMMEDIATE_THRESHOLD,
    WAREHOUSES,
    CREATED
FROM SNOWFLAKE.ACCOUNT_USAGE.RESOURCE_MONITORS
ORDER BY PCT_CONSUMED DESC;

-- =============================================================================
-- 9. V_COST_ANOMALIES - ML-detected spending anomalies
-- =============================================================================
CREATE OR REPLACE VIEW HELIOS_ANALYTICS_DB.PUBLIC.V_COST_ANOMALIES AS
SELECT 
    DATE AS ANOMALY_DATE,
    ANOMALY_ID,
    IS_ANOMALY,
    ROUND(ACTUAL_VALUE, 4) AS ACTUAL_CREDITS,
    ROUND(FORECASTED_VALUE, 4) AS FORECASTED_CREDITS,
    ROUND(ACTUAL_VALUE - FORECASTED_VALUE, 4) AS VARIANCE,
    ROUND(UPPER_BOUND, 4) AS UPPER_BOUND,
    ROUND(LOWER_BOUND, 4) AS LOWER_BOUND,
    CASE 
        WHEN IS_ANOMALY AND ACTUAL_VALUE > UPPER_BOUND * 1.5 THEN 'CRITICAL'
        WHEN IS_ANOMALY AND ACTUAL_VALUE > UPPER_BOUND THEN 'HIGH'
        WHEN ACTUAL_VALUE > FORECASTED_VALUE * 1.2 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS SEVERITY
FROM SNOWFLAKE.ACCOUNT_USAGE.ANOMALIES_DAILY
WHERE DATE >= DATEADD(DAY, -30, CURRENT_DATE())
ORDER BY DATE DESC;

-- =============================================================================
-- 10. V_MTD_BUDGET_TRACKER - Month-to-date vs 200 credit budget
-- =============================================================================
CREATE OR REPLACE VIEW HELIOS_ANALYTICS_DB.PUBLIC.V_MTD_BUDGET_TRACKER AS
WITH mtd_spend AS (
    SELECT 
        ROUND(SUM(CREDITS_USED), 4) AS MTD_CREDITS
    FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
    WHERE START_TIME >= DATE_TRUNC('MONTH', CURRENT_DATE())
),
daily_avg AS (
    SELECT 
        ROUND(AVG(daily_credits), 4) AS AVG_DAILY_CREDITS
    FROM (
        SELECT DATE_TRUNC('DAY', START_TIME)::DATE AS day, SUM(CREDITS_USED) AS daily_credits
        FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
        WHERE START_TIME >= DATE_TRUNC('MONTH', CURRENT_DATE())
        GROUP BY DATE_TRUNC('DAY', START_TIME)::DATE
    )
)
SELECT 
    200 AS MONTHLY_BUDGET,
    m.MTD_CREDITS,
    ROUND(200 - m.MTD_CREDITS, 4) AS REMAINING_CREDITS,
    ROUND((m.MTD_CREDITS / 200) * 100, 2) AS PCT_CONSUMED,
    d.AVG_DAILY_CREDITS AS DAILY_BURN_RATE,
    DAY(CURRENT_DATE()) AS DAYS_ELAPSED,
    DAY(LAST_DAY(CURRENT_DATE())) AS DAYS_IN_MONTH,
    DAY(LAST_DAY(CURRENT_DATE())) - DAY(CURRENT_DATE()) AS DAYS_REMAINING,
    ROUND(m.MTD_CREDITS + (d.AVG_DAILY_CREDITS * (DAY(LAST_DAY(CURRENT_DATE())) - DAY(CURRENT_DATE()))), 4) AS PROJECTED_MONTHLY,
    CASE 
        WHEN m.MTD_CREDITS + (d.AVG_DAILY_CREDITS * (DAY(LAST_DAY(CURRENT_DATE())) - DAY(CURRENT_DATE()))) > 200 THEN 'OVER BUDGET'
        WHEN m.MTD_CREDITS + (d.AVG_DAILY_CREDITS * (DAY(LAST_DAY(CURRENT_DATE())) - DAY(CURRENT_DATE()))) > 180 THEN 'AT RISK'
        ELSE 'ON TRACK'
    END AS BUDGET_STATUS
FROM mtd_spend m, daily_avg d;
