-- =============================================================================
-- RESOURCE MONITORS - Project Helios (Trial: 200 credits/month)
-- =============================================================================

-- Account-level safety net
CREATE OR REPLACE RESOURCE MONITOR HELIOS_ACCOUNT_MONITOR
  WITH CREDIT_QUOTA = 200
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 90 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND;

ALTER ACCOUNT SET RESOURCE_MONITOR = HELIOS_ACCOUNT_MONITOR;

-- Per-warehouse monitors (scaled for trial)
CREATE OR REPLACE RESOURCE MONITOR INGEST_WH_MONITOR
  WITH CREDIT_QUOTA = 30
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 70 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND;

ALTER WAREHOUSE INGEST_WH SET RESOURCE_MONITOR = INGEST_WH_MONITOR;

CREATE OR REPLACE RESOURCE MONITOR TRANSFORM_WH_MONITOR
  WITH CREDIT_QUOTA = 50
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 70 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND;

ALTER WAREHOUSE TRANSFORM_WH SET RESOURCE_MONITOR = TRANSFORM_WH_MONITOR;

CREATE OR REPLACE RESOURCE MONITOR REPORTING_WH_MONITOR
  WITH CREDIT_QUOTA = 30
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 70 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND;

ALTER WAREHOUSE REPORTING_WH SET RESOURCE_MONITOR = REPORTING_WH_MONITOR;

CREATE OR REPLACE RESOURCE MONITOR CORTEX_WH_MONITOR
  WITH CREDIT_QUOTA = 60
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 70 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND;

ALTER WAREHOUSE CORTEX_WH SET RESOURCE_MONITOR = CORTEX_WH_MONITOR;
