-- Quick health check - all views
SELECT 'V_DAILY_CREDIT_SUMMARY' AS VIEW_NAME, COUNT(*) AS ROW_COUNT FROM HELIOS_ANALYTICS_DB.PUBLIC.V_DAILY_CREDIT_SUMMARY
UNION ALL SELECT 'V_WAREHOUSE_DAILY_USAGE', COUNT(*) FROM HELIOS_ANALYTICS_DB.PUBLIC.V_WAREHOUSE_DAILY_USAGE
UNION ALL SELECT 'V_WAREHOUSE_HOURLY_PATTERN', COUNT(*) FROM HELIOS_ANALYTICS_DB.PUBLIC.V_WAREHOUSE_HOURLY_PATTERN
UNION ALL SELECT 'V_TOP_QUERIES_BY_COST', COUNT(*) FROM HELIOS_ANALYTICS_DB.PUBLIC.V_TOP_QUERIES_BY_COST
UNION ALL SELECT 'V_USER_CONSUMPTION', COUNT(*) FROM HELIOS_ANALYTICS_DB.PUBLIC.V_USER_CONSUMPTION
UNION ALL SELECT 'V_DATABASE_STORAGE', COUNT(*) FROM HELIOS_ANALYTICS_DB.PUBLIC.V_DATABASE_STORAGE
UNION ALL SELECT 'V_CORTEX_AI_USAGE', COUNT(*) FROM HELIOS_ANALYTICS_DB.PUBLIC.V_CORTEX_AI_USAGE
UNION ALL SELECT 'V_RESOURCE_MONITOR_STATUS', COUNT(*) FROM HELIOS_ANALYTICS_DB.PUBLIC.V_RESOURCE_MONITOR_STATUS
UNION ALL SELECT 'V_COST_ANOMALIES', COUNT(*) FROM HELIOS_ANALYTICS_DB.PUBLIC.V_COST_ANOMALIES
UNION ALL SELECT 'V_MTD_BUDGET_TRACKER', COUNT(*) FROM HELIOS_ANALYTICS_DB.PUBLIC.V_MTD_BUDGET_TRACKER;

-- Key views to inspect individually
SELECT * FROM HELIOS_ANALYTICS_DB.PUBLIC.V_MTD_BUDGET_TRACKER;           -- Budget status
SELECT * FROM HELIOS_ANALYTICS_DB.PUBLIC.V_RESOURCE_MONITOR_STATUS;      -- Monitor quotas
SELECT * FROM HELIOS_ANALYTICS_DB.PUBLIC.V_DAILY_CREDIT_SUMMARY LIMIT 7; -- Last 7 days
SELECT * FROM HELIOS_ANALYTICS_DB.PUBLIC.V_TOP_QUERIES_BY_COST LIMIT 10; -- Expensive queries