-- =============================================================================
-- RBAC SETUP - Project Helios
-- Role: SECURITYADMIN (required for role management)
-- Warehouse: COMPUTE_WH (admin operations)
-- =============================================================================

USE ROLE SECURITYADMIN;
USE WAREHOUSE COMPUTE_WH;

-- Create custom roles
CREATE ROLE IF NOT EXISTS HELIOS_BI_CONSUMER;
CREATE ROLE IF NOT EXISTS HELIOS_DATA_ANALYST;
CREATE ROLE IF NOT EXISTS HELIOS_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS HELIOS_SYSADMIN;
CREATE ROLE IF NOT EXISTS HELIOS_SECURITYADMIN;

-- Build role hierarchy (bottom-up inheritance)
-- HELIOS_BI_CONSUMER -> HELIOS_DATA_ANALYST -> HELIOS_DATA_ENGINEER -> HELIOS_SYSADMIN
GRANT ROLE HELIOS_BI_CONSUMER TO ROLE HELIOS_DATA_ANALYST;
GRANT ROLE HELIOS_DATA_ANALYST TO ROLE HELIOS_DATA_ENGINEER;
GRANT ROLE HELIOS_DATA_ENGINEER TO ROLE HELIOS_SYSADMIN;

-- Connect custom roles to system roles
GRANT ROLE HELIOS_SYSADMIN TO ROLE SYSADMIN;
GRANT ROLE HELIOS_SECURITYADMIN TO ROLE SECURITYADMIN;
