-- =============================================================================
-- WAREHOUSES - Project Helios
-- Role: SYSADMIN (required for warehouse creation)
-- Warehouse: N/A (creating warehouses)
-- =============================================================================

USE ROLE SYSADMIN;

-- Warehouse for data ingestion workloads
CREATE WAREHOUSE IF NOT EXISTS INGEST_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Warehouse for data transformation workloads
CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Warehouse for reporting and BI queries
CREATE WAREHOUSE IF NOT EXISTS REPORTING_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Warehouse for Cortex AI/ML workloads
CREATE WAREHOUSE IF NOT EXISTS CORTEX_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Grant USAGE on warehouses to HELIOS_DATA_ENGINEER
GRANT USAGE ON WAREHOUSE INGEST_WH TO ROLE HELIOS_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE HELIOS_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE REPORTING_WH TO ROLE HELIOS_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE CORTEX_WH TO ROLE HELIOS_DATA_ENGINEER;
